version: "3"
   
services:
  web:
    build: .
    command: bash -c "python djangoproject/manage.py runserver 0.0.0.0:8000 & python djangoproject/tetris_app/server.py"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "8001:8001"
