name: Deploy to QTPI

on:
  workflow_run:
    workflows: [ "Install Dependencies" ]
    types: [completed]

jobs:

  test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        pip3 install --upgrade pip
        pip3 install -r requirements.txt
        
    - uses: actions/checkout@v2
    - name: Run Tests
      run: |
        cd djangoproject
        python3 manage.py behave
