name: Build app

on: [push, pull_request]

jobs:
  build:
    defaults:
      run:
        working-directory: frontend

    name: Build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install --prefer-offline

      - name: Build frontend
        run: npm run build