name: Build app

on: [ push, pull_request ]

jobs:
  build:
    defaults:
      run:
        working-directory: frontend

    name: Build
    runs-on: self-hosted
    steps:
      - name: Get current date
        id: date
        run: |
          echo "::set-output name=date::$(date +'%Y-%m-%d')"
          echo ${{ steps.date.outputs.date }} > "src/build_time.txt"

      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn --prefer-offline

      - name: Build frontend
        run: npm run build

      - name: Discord Notification
        run:
          python ../discord_bot.py
          -t ${{ steps.date.outputs.date }}
          -b ${{github.ref_name}}
          -s ${{ github.event.workflow_run.conclusion == 'success' }}
          -p ${{ github.job }}