name: Build app

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Cache npm dependencies
        id: cache-npm-deps
        uses: actions/cache@v2
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        working-directory: frontend
        if: steps.cache-npm-deps.outputs.cache-hit != 'true'
        run: |
          ls -la
          npm install

      - name: Build frontend
        working-directory: frontend
        run: npm run build