name: Build app

on: [push, pull_request]

jobs:
  build:
    defaults:
      run:
        working-directory: frontend

    name: Build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache
        with:
          path: /home/pi/npm_cache/
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-

      - name: Install Dependencies
        run: npm install --no-registry --offline --prefer-offline -cache /home/pi/npm_cache/ --cache-min 999999999

      - name: Build frontend
        run: npm run build  # just work please