name: Install Dependencies

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache-npm-deps
        with:
          path: npm
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock;json') }}

      - name: Install dependencies
        working-directory: frontend
        if: steps.cache-npm-deps.outputs.cache-hit != 'true'
        run: npm ci --no-audit --prefer-offline

      - name: Build frontend
        working-directory: frontend
        run: npm run build