name: Build app

on: [push, pull_request]

jobs:
  build:
    defaults:
      run:
        working-directory: frontend

    name: Build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - uses: bahmutov/npm-install@v1
        with:
          working-directory: frontend

      - name: Build frontend
        run: npm run build  # just work please