name: Install Dependencies

on:
  workflow_run:
    workflows: [ "build markdown" ]
    types: [completed]

jobs:

  install-deps:
    defaults:
      run:
        working-directory: frontend

    runs-on: self-hosted

    steps:
      - name: Cache npm dependencies
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          working-directory: frontend
          path: './'
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build app
        run: npm run build
