name: Build app

on: [push, pull_request]

jobs:
  build:
    defaults:
      run:
        working-directory: frontend

    name: Build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - uses: c-hive/gha-npm-cache@v1

      - name: Install Dependencies
        run: npm install

      - name: Build frontend
        run: npm run build  # just work please