name: Install Dependencies

on: push

jobs:

  install-deps:
    defaults:
      run:
        working-directory: frontend

    runs-on: self-hosted

    steps:
    - name: Cache node modules
    - uses: |
        actions/checkout@v2
        actions/cache@v2
      id: cache-nodemodules
      env:
        cache-name: cache-node-modules
      with:
        # caching node_modules
        path: 'node_modules'
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install Dependencies
      if: steps.cache-nodemodules.outputs.cache-hit != 'true'
      run: npm ci

  build:
    defaults:
      run:
        working-directory: frontend

    runs-on: self-hosted

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Build app
      - uses: actions/checkout@v2
      - run: npm run build
