name: Django CI

on: push

jobs:
  build:

    runs-on: self-hosted
    defaults:
      run:
        working-directory: djangoproject 

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        python -m pip3 install --upgrade pip3
        pip3 install -r requirements.txt
    - name: Run Tests
      run: |
        python3 djangoproject/manage.py behave djangoproject/features/
