name: Django CI

on:
  workflow_dispatch:

jobs:

  test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        pip3 install --upgrade pip
        pip3 install -r requirements.txt
        
    - uses: actions/checkout@v2
    - name: Run Tests
      run: |
        cd djangoproject
        python3 manage.py behave
    
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - uses: c-hive/gha-npm-cache@v1
      with:
        directory: frontend
    - name: Build App
      run: |
        cd frontend
        npm i
        npm run build
        
