name: Django CI

on: push

jobs:
  build:

    runs-on: self-hosted
    defaults:
      run:
        working-directory: djangoproject 

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py behave
