name: Django CI

on: push

jobs:

  test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        pip3 install --upgrade pip
        pip3 install -r requirements.txt
        
    - uses: actions/checkout@v2
    - name: Run Tests
      run: |
        cd djangoproject
        python3 manage.py behave
    
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
    - name: Build App
      run: |
        cd frontend
        npm i
        npm run build

  discord:
    runs-on: self-hosted
    steps:
      - name: send message
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_APP_ID }}
          webhook_token: ${{ secrets.DISCORD_PUB_KEY }}
          color: "#48f442"
          username: "GitHub Bot"
          message: "A new commit has been pushed with custom color."
