name: Test and Build Phase

on: [ push, pull_request ]

jobs:

  test:
    runs-on: self-hosted
    steps:
      - name: Get current date
        id: date
        run: |
          echo "::set-output name=date::$(date +'%Y-%m-%d-%s %T')"
          echo ${{ steps.date.outputs.date }} > "src/build_time.txt"

      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          pip3 install --upgrade pip
          pip3 install -r requirements.txt

      - uses: actions/checkout@v2

      - name: Run Tests
        run: |
          cd djangoproject
          python3 manage.py behave

  build:
    defaults:
      run:
        working-directory: frontend

    name: Build
    runs-on: self-hosted
    steps:

      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn --prefer-offline

      - name: Build frontend
        run: npm run build

      - name: Discord Notification
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        run: |
          pip3 install -r ../requirements.txt
          python3 ../discord_bot.py -t ${{ steps.date.outputs.date }} -b ${{github.ref_name}} -s ${{ github.event.workflow_run.conclusion == 'success' }} -p ${{ github.job }}