name: Test and Build Phase

on: [ push, pull_request ]

# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error
# https://docs.github.com/en/actions/learn-github-actions/contexts

jobs:

  test:
    runs-on: self-hosted
    steps:

      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          pip3 install --upgrade pip
          pip3 install -r requirements.txt

      - name: Run Tests
        run: |
          cd djangoproject
          python3 manage.py behave

  build:
    needs: test
    defaults:
      run:
        working-directory: frontend

    name: Build
    runs-on: self-hosted
    steps:

      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn --prefer-offline

      - name: Build frontend
        run: npm run build

  notify:
    needs: build
    name: Discord Notification
    runs-on: self-hosted
    continue-on-error: true
    steps:
    - name: Discord Notification
      env:
        DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        DISCORD_CHANNEL_TOKEN: ${{ secrets.DISCORD_CHANNEL_TOKEN }}
      run: |
        echo "$(date +'%Y-%m-%d-%T')" ${{ github.ref_name }} ${{ runner.name }} ${{ github.actor }}
        python3 .github/discord_python/discord_bot.py -t "$(date +'%d %h %T')" -b ${{ github.ref_name }} -s ${{ needs.build.result }} -p ${{ github.run_id }} -r ${{ runner.name }} -a ${{ github.actor }} -c ${{ github.sha }}